src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("byte");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("short");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("int");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("long");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ubyte");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("ushort");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("uint");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("ulong");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("float");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("double");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("char");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("bool");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("String");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("Byte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("UByte");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("Short");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("UShort");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("Integer");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("UInteger");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("Long");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("ULong");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Float");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Double");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Pointer");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Char");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
src/cast.c:        *right_type = create_node_type_with_class_name("Bool");
Binary file src/cast.o matches
src/class_compiler.c:                *result_type = create_node_type_with_class_name("Null");
src/class_compiler.c:            *result_type = create_node_type_with_class_name("Null");
src/class_compiler.c:        *result_type = create_node_type_with_class_name("Null");
src/class_compiler.c:            sNodeType* result_type = create_node_type_with_class_name("Null");
src/class_compiler.c:            sNodeType* field_type = create_node_type_with_class_name("int");
src/class_compiler.c:            sNodeType* result_type = create_node_type_with_class_name("Null");
Binary file src/class_compiler.o matches
src/common.h:sNodeType* create_node_type_with_class_name(char* class_name);
src/common.h:sNodeType* create_node_type_with_generics_number(int generics_num);
src/common.h:sNodeType* create_node_type_with_method_generics_number(int generics_num);
src/common.h:sNodeType* create_node_type_with_class_pointer(sCLClass* klass);
src/klass_compile_time.c:        result->mGenericsTypes[i] = create_node_type_with_class_name(interface_name);
src/klass_compile_time.c:            result_type1 = create_node_type_with_class_pointer(klass2);
src/klass_compile_time.c:                param1_type = create_node_type_with_class_pointer(klass2);
Binary file src/klass_compile_time.o matches
src/method_compiler.c:            node_type->mGenericsTypes[i] = create_node_type_with_class_name(class_name);
Binary file src/method_compiler.o matches
src/node.c:        info->type = create_node_type_with_class_name("byte");
src/node.c:        info->type = create_node_type_with_class_name("ubyte");
src/node.c:        info->type = create_node_type_with_class_name("short");
src/node.c:        info->type = create_node_type_with_class_name("ushort");
src/node.c:        info->type = create_node_type_with_class_name("int");
src/node.c:        info->type = create_node_type_with_class_name("uint");
src/node.c:        info->type = create_node_type_with_class_name("long");
src/node.c:        info->type = create_node_type_with_class_name("ulong");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("byte");
src/node.c:        info->type = create_node_type_with_class_name("ubyte");
src/node.c:        info->type = create_node_type_with_class_name("short");
src/node.c:        info->type = create_node_type_with_class_name("ushort");
src/node.c:        info->type = create_node_type_with_class_name("int");
src/node.c:        info->type = create_node_type_with_class_name("uint");
src/node.c:        info->type = create_node_type_with_class_name("long");
src/node.c:        info->type = create_node_type_with_class_name("ulong");
src/node.c:        info->type = create_node_type_with_class_name("float");
src/node.c:        info->type = create_node_type_with_class_name("double");
src/node.c:        info->type = create_node_type_with_class_name("null");
src/node.c:        info->type = create_node_type_with_class_name("char");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:                info->type = create_node_type_with_class_name("ulong");
src/node.c:                sNodeType* ulong_type = create_node_type_with_class_name("ulong");
src/node.c:                    info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            sNodeType* ulong_type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:            right_type = create_node_type_with_class_name("int");
src/node.c:            right_type = create_node_type_with_class_name("uint");
src/node.c:            right_type = create_node_type_with_class_name("byte");
src/node.c:            right_type = create_node_type_with_class_name("ubyte");
src/node.c:            right_type = create_node_type_with_class_name("short");
src/node.c:            right_type = create_node_type_with_class_name("ushort");
src/node.c:            right_type = create_node_type_with_class_name("long");
src/node.c:            right_type = create_node_type_with_class_name("ulong");
src/node.c:            right_type = create_node_type_with_class_name("float");
src/node.c:            right_type = create_node_type_with_class_name("double");
src/node.c:            info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("bool");
src/node.c:                info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("bool");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("byte");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("byte");
src/node.c:    param_types[0] = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("Byte");
src/node.c:    info->type = create_node_type_with_class_name("float");
src/node.c:    param_types[0] = create_node_type_with_class_name("float");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("Float");
src/node.c:    info->type = create_node_type_with_class_name("double");
src/node.c:    param_types[0] = create_node_type_with_class_name("double");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("Double");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("ubyte");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("ubyte");
src/node.c:    param_types[0] = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("UByte");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("short");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("short");
src/node.c:    param_types[0] = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("Short");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("ushort");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("ushort");
src/node.c:    param_types[0] = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("UShort");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("int");
src/node.c:    info->type = create_node_type_with_class_name("int");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("int");
src/node.c:    param_types[0] = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("Integer");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("uint");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("uint");
src/node.c:    param_types[0] = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("UInteger");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("long");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("long");
src/node.c:    param_types[0] = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("Long");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("ulong");
src/node.c:    gNodes[node].mType = create_node_type_with_class_name("ulong");
src/node.c:    param_types[0] = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        sNodeType* result_type2 = create_node_type_with_class_name("ULong");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                if_result_type = create_node_type_with_class_name("Anonymous");
src/node.c:            if_result_type = create_node_type_with_class_name("Anonymous");
src/node.c:            info->type = create_node_type_with_class_name("String");
src/node.c:            info->type = create_node_type_with_class_name("String");
src/node.c:            param_types[0] = create_node_type_with_class_name("String");
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                when_result_type = create_node_type_with_class_name("Anonymous");
src/node.c:                    info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                    info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                    when_result_type = create_node_type_with_class_name("Anonymous");
src/node.c:                        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                    info->type = create_node_type_with_class_name("bool");
src/node.c:                        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                            sNodeType* result_type = create_node_type_with_class_name("bool");
src/node.c:                            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                            sNodeType* result_type = create_node_type_with_class_name("bool");
src/node.c:                            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                    when_result_type = create_node_type_with_class_name("Anonymous");
src/node.c:            when_result_type = create_node_type_with_class_name("Anonymous");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("Null");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("Null");
src/node.c:    info->type = create_node_type_with_class_name("Null");
src/node.c:    info->type = create_node_type_with_class_name("bool");
src/node.c:    info->type = create_node_type_with_class_name("bool");
src/node.c:    info->type = create_node_type_with_class_name("Null");
src/node.c:    info->type = create_node_type_with_class_name("WildCard");
src/node.c:            result->mGenericsTypes[i] = create_node_type_with_class_pointer(generics_param->mInterface[i]);
src/node.c:            result->mGenericsTypes[i] = create_node_type_with_class_pointer(generics_param->mInterface[i]);
src/node.c:                    info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            sNodeType* result_type = create_node_type_with_class_name("Anonymous");
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                        sNodeType* right_type = create_node_type_with_class_name(cast_type_name);
src/node.c:                        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("String");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("Null");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("Anonymous");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name(class_name);
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:            var->mType = create_node_type_with_class_name(class_name);
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        value_result_type = create_node_type_with_class_name("Null");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("Null");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("Null");
src/node.c:            info->type = create_node_type_with_class_name("Null");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int");
src/node.c:        info->type = create_node_type_with_class_name("char");
src/node.c:        info->type = create_node_type_with_class_name("char");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("bool");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int");
src/node.c:            info->type = create_node_type_with_class_name("uint");
src/node.c:            info->type = create_node_type_with_class_name("byte");
src/node.c:            info->type = create_node_type_with_class_name("ubyte");
src/node.c:            info->type = create_node_type_with_class_name("short");
src/node.c:            info->type = create_node_type_with_class_name("ushort");
src/node.c:            info->type = create_node_type_with_class_name("long");
src/node.c:            info->type = create_node_type_with_class_name("ulong");
src/node.c:            info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* int_type = create_node_type_with_class_name("int");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* int_type = create_node_type_with_class_name("int");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("char");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("String");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("Buffer");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("Path");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("pointer");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("pointer");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* array_type = create_node_type_with_class_name("Array");
src/node.c:        array_type->mGenericsTypes[0] = create_node_type_with_class_name("Object");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* array_type = create_node_type_with_class_name("EqualableArray");
src/node.c:        array_type->mGenericsTypes[0] = create_node_type_with_class_name("Object");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* array_type = create_node_type_with_class_name("SortableArray");
src/node.c:        array_type->mGenericsTypes[0] = create_node_type_with_class_name("Object");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* list_type = create_node_type_with_class_name("List");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* list_type = create_node_type_with_class_name("SortableList");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* list_type = create_node_type_with_class_name("EqualableList");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* tuple_type = create_node_type_with_class_name(class_name);
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                        left_element_type = create_node_type_with_class_pointer(left_class->mBoxingClass);
src/node.c:                    info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("Null");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* hash_type = create_node_type_with_class_name("Hash");
src/node.c:        info->type = create_node_type_with_class_name("lambda");
src/node.c:                node_block_type->mResultType = create_node_type_with_class_name("Null");
src/node.c:    sNodeType* lambda_type = create_node_type_with_class_name("lambda");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:                info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("regex");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    info->type = create_node_type_with_class_name("bool");
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:        info->type = create_node_type_with_class_name("int"); // dummy
src/node.c:    sNodeType* node_type = create_node_type_with_class_name("Range");
src/node.c:            info->type = create_node_type_with_class_name("int"); // dummy
Binary file src/node.o matches
src/node_block.c:        info->type = create_node_type_with_class_name("Null");
src/node_block.c:                info->type = create_node_type_with_class_name("Null");
src/node_block.c:        info->type = create_node_type_with_class_name("Null");
src/node_block.c:            info->type = create_node_type_with_class_name("Null");
Binary file src/node_block.o matches
src/node_type.c:sNodeType* create_node_type_with_class_pointer(sCLClass* klass)
src/node_type.c:sNodeType* create_node_type_with_class_name(char* class_name)
src/node_type.c:sNodeType* create_node_type_with_generics_number(int generics_num)
src/node_type.c:    return create_node_type_with_class_name(class_name);
src/node_type.c:sNodeType* create_node_type_with_method_generics_number(int generics_num)
src/node_type.c:    return create_node_type_with_class_name(class_name);
src/node_type.c:    return substitution_posibility(left, create_node_type_with_class_name(right_class_name), NULL , NULL, NULL, NULL);
src/node_type.c:    return operand_posibility(left, create_node_type_with_class_name(right_class_name), op_string);
src/node_type.c:    return type_identify(left, create_node_type_with_class_name(right_class_name));
src/node_type.c:        result->mGenericsTypes[i] = create_node_type_with_class_pointer(interface);
src/node_type.c:            sNodeType* boxing_type = create_node_type_with_class_pointer(klass->mBoxingClass);
src/node_type.c:    sNodeType* primitive_type = create_node_type_with_class_pointer(primitive_class);
src/node_type.c:        sNodeType* node_type = create_node_type_with_class_pointer(klass);
Binary file src/node_type.o matches
src/parser.c:            result_type = create_node_type_with_class_name("Null");
src/parser.c:        result_type = create_node_type_with_class_name("Null");
src/parser.c:                sNodeType* command_class = create_node_type_with_class_name("Command");
src/parser.c:            *result_type = create_node_type_with_method_generics_number(i);
src/parser.c:            *result_type = create_node_type_with_generics_number(i);
src/parser.c:            *result_type = create_node_type_with_class_pointer(info->klass);
src/parser.c:            *result_type = create_node_type_with_class_name(type_name);
src/parser.c:            node_block_type->mResultType = create_node_type_with_class_name("Null");
src/parser.c:            *result_type = create_node_type_with_generics_number(i);
src/parser.c:            *result_type = create_node_type_with_method_generics_number(i);
src/parser.c:            *result_type = create_node_type_with_class_pointer(info->klass);
src/parser.c:            *result_type = create_node_type_with_class_name(type_name);
src/parser.c:            node_block_type->mResultType = create_node_type_with_class_name("Null");
src/parser.c:        result_type = create_node_type_with_class_name("Null");
src/parser.c:        result_type = create_node_type_with_class_name("Null");
Binary file src/parser.o matches
