.TH CLOVER2 1
.SH NAME
Clover2 computer language

cclover2 [source file(.clcl or .cl)] 
clover2 [source file(.cl)]
iclover2
.PP

.SH DESCRIPTION
cclover2 is the compiler for Clover2. clover2 is the Virtual Machine for Clover2. iclover2 is REPL for Clover2.
.SH USAGE
SEE https://github.com/ab25cq/clover2/wiki or /usr/share/doc/clover2/*.md files(Japanese or English)
.br

.SH COPYRIGHT
(C) Copyright 2018 Daisuke Minato <ab25cq@gmail.com>
