dep1:
	cclover2 Dep1.clc
hello:
	cclover2 Hello.cl
	clover2 Hello.clo
hello_:
	clover2 Hello.cl
hello2:
	cclover2 Hello2.clc
	cclover2 Hello2.cl
	clover2 Hello2.clo
hello2_:
	clover2 Hello2.clc Hello2.cl
fun:
	clover2 fun.cl
clean:
	rm -rf *.clcl *.clo

